import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Page } from "@/components/Header/Header.config";
import Contacts from "@/components/Contacts/Contacts";
import AdvertisementHero from "@/components/Advertisement/AdvertisementHero/AdvertisementHero";
import AdvertisementNotForAll from "@/components/Advertisement/AdvertisementNotForAll/AdvertisementNotForAll";
import AdvertisementAnalize from "@/components/Advertisement/AdvertisementAnalize/AdvertisementAnalize";
import AdvertisementStrategy from "@/components/Advertisement/AdvertisementStrategy/AdvertisementStrategy";
import AdvertisementAgreement from "@/components/Advertisement/AdvertisementAgreement/AdvertisementAgreement";
import AdvertisementSearch from "@/components/Advertisement/AdvertisementSearch/AdvertisementSearch";
import AdvertisementAreYouAgree from "@/components/Advertisement/AdvertisementAreYouAgree/AdvertisementAreYouAgree";
import AdvertisementCompany from "@/components/Advertisement/AdvertisementCompany/AdvertisementCompany";
import AdvertisementTest from "@/components/Advertisement/AdvertisementTest/AdvertisementTest";
import AdvertisementFix from "@/components/Advertisement/AdvertisementFix/AdvertisementFix";
import AdvertisementFinal from "@/components/Advertisement/AdvertisementFinal/AdvertisementFinal";
import AdvertisementReports from "@/components/Advertisement/AdvertisementReports/AdvertisementReports";
import AdvertisementWarranty from "@/components/Advertisement/AdvertisementWarranty/AdvertisementWarranty";
import AdvertisementWeAreNotTheBest from "@/components/Advertisement/AdvertisementWeAreNotTheBest/AdvertisementWeAreNotTheBest";
import AdvertisementQandA from "@/components/Advertisement/AdvertisementQandA/AdvertisementQandA";
import AdvertisementTuning from "@/components/Advertisement/AdvertisementTuning/AdvertisementTuning";
import { GetServerSidePropsContext } from "next";
import { getIsSsrMobile } from '../../utils/isSSRMoblile';
import MobileHeader from "@/components/MobileHeader/MobileHeader";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      isSsrMobile: getIsSsrMobile(context)
    }
  }
}

export default function Advertisement({
  isSsrMobile,
}: {
  isSsrMobile: boolean,
}) {

  const isMobile = isSsrMobile

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {
          isMobile ?
            <MobileHeader /> :
            <Header page={Page.home} />
        }
        <AdvertisementHero />
        <AdvertisementNotForAll />
        <AdvertisementAnalize isMobile={isMobile} />
        <AdvertisementStrategy isMobile={isMobile} />
        <AdvertisementAgreement isMobile={isMobile} />
        <AdvertisementSearch isMobile={isMobile} />
        <AdvertisementAreYouAgree />
        <AdvertisementCompany />
        {/* <AdvertisementTest />
        <AdvertisementFix />
        <AdvertisementFinal />
        <AdvertisementReports />
        <AdvertisementWarranty />
        <AdvertisementTuning advType='КОНТЕКСТНОЙ' />
        <AdvertisementWeAreNotTheBest />
        <AdvertisementQandA />
        <Contacts /> */}
        <Footer />
      </main>
    </>
  );
}
