import React from 'react'
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Page } from "@/components/Header/Header.config";
import { GetServerSidePropsContext } from 'next';
import { getIsSsrMobile } from '@/utils/isSSRMoblile';
import MobileHeader from '@/components/MobileHeader/MobileHeader';
import ShopCategoriesHero from '@/components/Shop/ShopCategoriesHero/ShopCategoriesHero';
import { h1, menuBlockArr } from '../../components/Product/pagesFiles/models.config';

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      isSsrMobile: getIsSsrMobile(context)
    },
  };
}


const inter = Inter({ subsets: ["latin"] });

export default function Models({
  isSsrMobile,
}: {
  isSsrMobile: boolean,
}) {

  const isMobile = isSsrMobile

  return (
    <>
      <Head>
        <title>Vehicles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {
          isMobile ?
            <MobileHeader /> :
            <Header page={Page.shop} />
        }
        <ShopCategoriesHero
          h1={h1}
          menuBlockArr={menuBlockArr}
        />
        <Footer />
      </main>
    </>
  );
}
