import { useRouter } from "next/router";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "./Product.module.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Page } from "@/components/Header/Header.config";
import React, { useState } from 'react'
import defaultImage1 from './assets/defaultImage1.png'
import { ProductPage } from "./Product.typings";
import BreadCrumbs from "@/components/Product/BreadCrumbs/BreadCrumbs";
import ProductHero from "@/components/Product/ProductHero/ProductHero";

const inter = Inter({ subsets: ["latin"] });

export default function PageOfGood() {

  const [goodsArray, setGoodsArray] = useState<ProductPage[]>([
    {
      productId: 1,
      productName:'Renault Duster',
      categoryTitle: 'Транспорт',
      categoryLink:'/shop/vehicles',
      subcategoryTitle: 'Кроссовер',
      subcategoryLink:'/',
      slug:'renault-duster1',
      images:[
        {
          id:1,
          image:defaultImage1,
          isMain:true,
        },
        {
          id:2,
          image:defaultImage1,
          isMain:false,
        },
        {
          id:3,
          image:defaultImage1,
          isMain:false,
        },
        {
          id:4,
          image:defaultImage1,
          isMain:false,
        },
        {
          id:5,
          image:defaultImage1,
          isMain:false,
        },
      ]
    },
  ])

  const findSlugItem = () => {
      const foundItem = goodsArray.find(item => item.slug === router.query.slug)
      if (foundItem) return foundItem
  }

  const router = useRouter()
  const itemSlug = findSlugItem()


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header page={Page.shop} />
        {
          itemSlug &&
          <div className={styles.content}>
            <BreadCrumbs
              categoryTitle={itemSlug.categoryTitle}
              categoryLink={itemSlug.categoryLink}
              subcategoryTitle={itemSlug.subcategoryTitle}
              subcategoryLink={itemSlug.subcategoryLink}
              productName={itemSlug.productName}
            />
            <ProductHero
              
            />
          </div>
        }
        <Footer />
      </main>
    </>
  );
}
