import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
import { Page } from "@/components/Header/Header.config";
import Account from "@/components/Account/Account";
import Footer from "@/components/Footer/Footer";
import { useRouter } from "next/router";
import { GetServerSidePropsContext } from "next";
import { getIsSsrMobile } from "@/utils/isSSRMoblile";
import MobileHeader from "@/components/MobileHeader/MobileHeader";
import {useEffect} from 'react';

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      isSsrMobile: getIsSsrMobile(context)
    }
  }
}

export default function Shop({
  isSsrMobile,
}: {
  isSsrMobile: boolean,
}) {

  const isMobile = isSsrMobile
  const loadingScreen = useRouter().query.loadingScreen
  const routerQuery = Number(loadingScreen) || 1
  //const routerQuery = useRouter().query.loadingScreen ? Number(useRouter().query.loadingScreen) : undefined

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {
          isMobile ?
            <MobileHeader /> :
            <Header page={Page.shop} />
        }
        <Account routerScreen={routerQuery} isMobile={isMobile}/>
        <Footer />
      </main>
    </>
  );
}
