import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from "@/components/Hero/Hero";
import Header from "@/components/Header/Header";
import Shop from "@/components/Shop/Shop";
import WhyAreTheyTrustUs from "@/components/WhyAreTheyTrustUs/WhyAreTheyTrustUs";
import ContactUs from "@/components/ContactUs/ContactUs";
import Reviews from "@/components/Reviews/Reviews";
import Contacts from "@/components/Contacts/Contacts";
import Footer from "@/components/Footer/Footer";
import { Page } from "@/components/Header/Header.config";
import { getIsSsrMobile } from "@/utils/isSSRMoblile";
import { GetServerSidePropsContext } from "next";
import MobileHeader from "@/components/MobileHeader/MobileHeader";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      isSSRMobile: getIsSsrMobile(context),
    },
  };
}

export default function Home({
  isSSRMobile
}:{
  isSSRMobile:boolean
}) {

  const isMobile = isSSRMobile

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {
          isMobile ?
          <MobileHeader /> :
          <Header page={Page.home}/>
        }
        <Hero />
        <Shop />
        <WhyAreTheyTrustUs />
        <ContactUs />
        <Reviews />
        <Contacts />
        <Footer />
      </main>
    </>
  );
}
