export const topMenu = [
    {
        id:1,
        title:'Профиль',
        link:'/account',
    },
    {
        id:2,
        title:'Избранное',
        link:'/account',
    },
    {
        id:3,
        title:'Корзина',
        link:'/account',
    },
    {
        id:4,
        title:'Отзывы',
        link:'/account',
    },
    {
        id:5,
        title:'Покупки',
        link:'/account',
    },
    {
        id:6,
        title:'Мои вопросы и ответы',
        link:'/account',
    },
]

export const middleMenu = [
    {
        id:1,
        title:'Решения',
        link:'/mobileSolutions',
    },
    {
        id:2,
        title:'Магазин',
        link:'/shop',
    },
    {
        id:3,
        title:'Форум',
        link:'#',
    },
    {
        id:4,
        title:'Блог',
        link:'#',
    },
    {
        id:5,
        title:'Академия',
        link:'#',
    },
    {
        id:6,
        title:'Карьера',
        link:'#',
    },
]

export const bottomMenu = [
    {
        id:1,
        title:'Русский',
        link:'#',
    },
    {
        id:2,
        title:'RUB',
        link:'#',
    },
]