import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Page } from "@/components/Header/Header.config";
import LandingPageHero from "@/components/LandingPage/LandingPageHero/LandingPageHero";
import LandingPageLiesAbout from "@/components/LandingPage/LandingPageLiesAbout/LandingPageLiesAbout";
//import LandingPageBestPractices from "@/components/LandingPage/LandingPageBestPractices/LandingPageBestPractices";
import LandingPageMoreThan from "@/components/LandingPage/LandingPageMoreThan/LandingPageMoreThan";
import LandingPageEmotions from "@/components/LandingPage/LandingPageEmotions/LandingPageEmotions";
import LandingPageDoYouHaveSite from "@/components/LandingPage/LandingPageDoYouHaveSite/LandingPageDoYouHaveSite";
import LandingPageStructure from "@/components/LandingPage/LandingPageStructure/LandingPageStructure";
import LandingPageBrief from "@/components/LandingPage/LandingPageBrief/LandingPageBrief";
import LandingPageFeatures from "@/components/LandingPage/LandingPageFeatures/LandingPageFeatures";
import LandingPageTrustUs from "@/components/LandingPage/LandingPageTrustUs/LandingPageTrustUs";
import LandingPageLongDev from "@/components/LandingPage/LandingPageLongDev/LandingPageLongDev";
import LandingPageValuable from "@/components/LandingPage/LandingPageValuable/LandingPageValuable";
import LandingPageMercedes from "@/components/LandingPage/LandingPageMercedes/LandingPageMercedes";
import LandingPageMainIdea from "@/components/LandingPage/LandingPageMainIdea/LandingPageMainIdea";
import LandingPageImportant from "@/components/LandingPage/LandingPageImportant/LandingPageImportant";
import LandingPageQandA from "@/components/LandingPage/LandingPageQandA/LandingPageQandA";
import Contacts from "@/components/Contacts/Contacts";
import { GetServerSidePropsContext } from "next";
import { getIsSsrMobile } from '../../utils/isSSRMoblile';
import MobileHeader from "@/components/MobileHeader/MobileHeader";
import MobileFooter from "@/components/MobileFooter/MobileFooter";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      isSsrMobile: getIsSsrMobile(context)
    }
  }
}

export default function LandingPage({
  isSsrMobile,
}: {
  isSsrMobile: boolean,
}) {

  const isMobile = isSsrMobile

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {
          isMobile ?
            <MobileHeader /> :
            <Header page={Page.home} />
        }
        <LandingPageHero isMobile={isMobile} />
        <LandingPageLiesAbout />
        {/* <LandingPageBestPractices /> */}
        <LandingPageMoreThan isMobile={isMobile} />
        <LandingPageEmotions isMobile={isMobile} />
        <LandingPageDoYouHaveSite />
        <LandingPageStructure />
        <LandingPageBrief isMobile={isMobile} />
        <LandingPageFeatures isMobile={isMobile} />
        <LandingPageTrustUs />
        <LandingPageLongDev />
        <LandingPageValuable isMobile={isMobile} />
        <LandingPageMercedes isMobile={isMobile} />
        <LandingPageMainIdea isMobile={isMobile} />
        <LandingPageImportant isMobile={isMobile} />
        <LandingPageQandA isMobile={isMobile} />
        <Contacts isMobile={isMobile} />
        {isMobile && <MobileFooter />}
        <Footer />
      </main>
    </>
  );
}
